### PR TITLE
Add custom-setup stanze, allow directory-1.3

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by polarina** [comment]
What is `custom-setup` needed for?

**Comment by phadej** [comment]
@polarina https://www.well-typed.com/blog/2015/07/cabal-setup-deps/

**Comment by lukexi** [comment]
Would be great to get this in and up for next stackage 8.0.2 nightly!

**Comment by schell** [comment]
Yes, I need this as well! :) 👍

**Comment by polarina** [comment]
@phadej I am not able to build this package with this change merged. Can you investigate?

```
$ cabal configure
Resolving dependencies...
[1 of 6] Compiling Registry         ( Registry.hs, dist/setup/Registry.o )
[2 of 6] Compiling Parser           ( Parser.hs, dist/setup/Parser.o )
[3 of 6] Compiling Utils            ( Utils.hs, dist/setup/Utils.o )
[4 of 6] Compiling Module           ( Module.hs, dist/setup/Module.o )
[5 of 6] Compiling Generator        ( Generator.hs, dist/setup/Generator.o )

Generator.hs:16:1: error:
    Failed to load interface for ‘Control.Monad.Trans.State’
    It is a member of the hidden package ‘transformers-0.5.2.0@transformers-0.5.2.0-CBIhyckC4NAL7Dt3UiLLVr’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.2.0@transformers-0.5.2.0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

Generator.hs:21:1: error:
    Failed to load interface for ‘Data.Map’
    It is a member of the hidden package ‘containers-0.5.7.1’.
    Perhaps you need to add ‘containers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

Generator.hs:22:1: error:
    Failed to load interface for ‘Data.Map’
    It is a member of the hidden package ‘containers-0.5.7.1’.
    Perhaps you need to add ‘containers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

Generator.hs:23:1: error:
    Failed to load interface for ‘Data.Set’
    It is a member of the hidden package ‘containers-0.5.7.1’.
    Perhaps you need to add ‘containers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

Generator.hs:24:1: error:
    Failed to load interface for ‘Data.Set’
    It is a member of the hidden package ‘containers-0.5.7.1’.
    Perhaps you need to add ‘containers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.```

**Comment by ekmett** [comment]
@phadej: This one uses a bit more custom setup than my usual.

**Comment by RyanGlScott** [comment]
Superseded by bcf343545bc499dac7b2a43854c9aa72450d9127?

**Comment by ekmett** [comment]
Looks like!

**Pull request closed without merging**
