### PR TITLE
Modernize haskell-ci–generated .travis.yml

### LINKED ISSUE #17: gl and `cabal new-build` don't mix
I recently attempted to switch the Travis infrastructure in this repo to use `cabal new-build`, which caused everything to break in unique and mysterious ways.

On GHC 7.8 and 7.10, [running `cabal sdist` simply fails with](https://travis-ci.org/ekmett/gl/jobs/329172290#L667):

```
$ (cd "." && cabal sdist)
cabal: The package 'gl' requires Cabal library version >=1.12.0 && >=1.24 but
no suitable version is installed.
```

I haven't the foggiest idea where that `>=1.12.0` constraint is coming from, as [`gl.cabal` requires `>=1.24`](https://github.com/ekmett/gl/blob/73b245e93d2df5d19ee341155515b7ccf306e4b9/gl.cabal#L14).

On GHC 8.0 and later, the [build fails at the custom setup](https://travis-ci.org/ekmett/gl/jobs/329172292#L663):

```
$ (cd "." && cabal sdist)
[1 of 6] Compiling Registry         ( Registry.hs, dist/setup/Registry.o )
[2 of 6] Compiling Parser           ( Parser.hs, dist/setup/Parser.o )

Parser.hs:18:1: error:
    Could not find module ‘Text.XML.HXT.Core’
    Use -v to see a list of the files searched for.
   |
18 | import Text.XML.HXT.Core
   | ^^^^^^^^^^^^^^^^^^^^^^^^
```

This is despite the fact that `custom-setup` does, in fact, [depend on `hxt`](https://github.com/ekmett/gl/blob/73b245e93d2df5d19ee341155515b7ccf306e4b9/gl.cabal#L30), which exports this module.

I'm way out of my element in debugging this... @hvr, any thoughts?

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #17.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Hm, Travis doesn't appear to be firing up on this PR for some reason. Is it currently enabled?

**Comment by RyanGlScott** [comment]
Could you perhaps look into enabling Travis integration for this repo, @ekmett?

**Comment by RyanGlScott** [comment]
Pinging @ekmett.

**Comment by RyanGlScott** [comment]
Hm, the [Travis setup for `lens-action`](https://travis-ci.org/ekmett/lens-action) doesn't appear to be responsive either...

**Comment by ekmett** [comment]
Hrmm.

**Comment by ekmett** [comment]
Triggered and enabled. Not sure how it got disabled.

**Comment by RyanGlScott** [comment]
Thanks, @ekmett! I should probably open a new PR for this anyway, since I can now use `haskell-ci-0.6` to accomplish this instead of the pre-release `haskell-ci` version I was using in this PR.

**Pull request closed without merging**
